! Generated by T. MINAMI on 2015.09.17
!
integer ( kind = 4 ) :: itflag ! 4 -> linear tetra,  10 -> quadratic tetra
parameter ( itflag = 4)
!### zmin and zmax
real(8),parameter :: zmin= -5.d+2, zmax=1.d+3
real(8),parameter ::  xin=1.5d0, yin=1.5d0  ! focus area extention [km]
! Nakadake first crater in WGS
real(8),parameter :: latorigin=32.884882d0, lonorigin=131.084782d0
!# conversion parameters TKY2WGS  calculated on http://vldb.gsi.go.jp/sokuchi/surveycalc/tky2jgd/main.html
real(8),parameter :: latshift=32.888250889 - latorigin     ! WGS = TKY + latshift
real(8),parameter :: lonshift=131.082413742 - lonorigin  ! ! WGS = TKY + lonshift
!
real(8),parameter :: sizein=0.02d0, sizefocus=30.d0, sizebo=300.d0
real(8) :: lc=sizebo          !  triangularsize on calculation boundaries
real(8) :: lc0=sizein         !  triangular size on calculation fiocus area
real(8) :: lc1=sizein*0.4  !  trianbgular size in electrode rectagulars
real(8) :: lc2=sizein*0.7  !  triangular size on the ecllipse for transmitter region
real(8) :: lc3=sizein*0.5  !  lc3 is size of triangles on circles
real(8) :: radius=sizein    !  radius of circles for receivers region
! south west point ( -xin, -yin), north east point (xin, yin)
real(8),parameter ::  xout=500.d0, yout=500.d0  ! whole area
! south west point ( -xout, -yout), north east point (xout, yout)
!### file headers ###
character(50) :: header2d="nakadake2d" ! -> header2d.geo, header2d.msh
character(50) :: header3d="nakadake3d" ! -> header3d.geo, header2d.msh
real(8)  :: earthrad, pi, d2r, dmu
!parameter( earthrad=6378.137d0, pi=4.d0*datan(1.d0),d2r=pi/180.,dmu=4.d0*pi*1.d-7)
parameter( pi=4.d0*datan(1.d0),d2r=pi/180.,dmu=4.d0*pi*1.d-7) ! earthrad is not used no more
!### topo files
character(50) :: centertopo="../topo/aso_caldera/aso_caldera.dat"
character(50) :: broadtopo="../topo/topo127_134_29_36.xyz"
! nmax, nemax
integer(4) :: nmax,nemax !nmax is the max # of nodes/lines in horizontal  2D mesh
parameter (nmax=41062,nemax=82958)
! Point of electrode of transmitter WGS
real(8),parameter :: sourcecurrent=10.d0 ! electric current through the wire [A]
real(8),dimension(2) :: lonlatelectrode1(1:2)=(/131.0784333, 32.8908028/) ! west point
real(8),dimension(2) :: lonlatelectrode2(1:2)=(/131.0814639,  32.8912333/) ! east point
! Point of receivers (WGS)
real(8),dimension(2) :: lonlatTRM(1:2)=(/ 131.080419, 32.891167/) !TRM
integer(4),parameter :: nobs=4
real(8),dimension(2),parameter :: lonlatA02(1:2)=(/ 131.083411, 32.886706/) ! A02
real(8),dimension(2),parameter :: lonlatA04(1:2)=(/ 131.081939, 32.884808/) ! A04
real(8),dimension(2),parameter :: lonlatA01(1:2)=(/ 131.083367, 32.882725/) ! A01
real(8),dimension(2),parameter :: lonlatA03(1:2)=(/ 131.086847, 32.881981/) ! A03
real(8) :: obslonlat(nobs,2)
data obslonlat(1,1:2) /lonlatA01(1),lonlatA01(2)/
data obslonlat(2,1:2) /lonlatA02(1),lonlatA02(2)/
data obslonlat(3,1:2) /lonlatA03(1),lonlatA03(2)/
data obslonlat(4,1:2) /lonlatA04(1),lonlatA04(2)/
real(8), parameter :: widthelectrodebox=0.010d0 ! [km]
